language: php

sudo: false

php:
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - composer run-script test
